version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - "3307:3306"
    restart: always

  web:
    image: php:8-apache
    container_name: docker-php
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
